language: node_js
node_js: 9.0.0
dist: trusty
sudo: required
branches:
  only:
    - master
    - develop
    - a-demo
    - e-demo
    - i-demo

cache:
  directories:
  - SimpleChart-AppA/node_modules
  - SimpleChart-AppE/node_modules
  - SimpleChart-AppI/node_modules

before_install:
  cd SimpleChart-AppE

before_script:
  - npm install -g @angular/cli

script:
  - ng build --aot

deploy:
  - provider: heroku
    api_key:
      secure: $HEROKU_KEY_USER_PABLOIN
    app:
      master: cicd-app
      develop: cicd-app-dev
      a-demo: cicd-aaa
      e-demo: cicd-eee
      i-demo: cicd-iii
    on:
      repo: Pabloin/CI-CD-app-Angular-Travis-Heroku

notifications:
  slack:
    rooms:
      secure: FGv8whPVcomzK+XEhRpCoSX+GAbJ/yVws0bc6j132EZ3M5483aGRu5vL5Svex+KjwkUF3KaQsf5gbCPk1lge3H/TyEAPrSmHmPzD/sjpOliljLp2qbDkVCcmAznUjv29UH4WE7a+hk/EX9kYkGUBCCn7t16hLp5zkv+IZOKYvIqyN3tUHS8mT0tcSipHbE/pFq4YdGwJKYTSm0mqDtK6NhBsnSB1tWyfIqCcPX1C2l2kClT9X4nhTI7oHCxBdXwwSvqNgY7QZlsac9F0IpyI3pemMWW8HJmuStD3iasDEBBJDBUgLJb12hEQM9tFLfZ8MIFPG6ZFHcHI5JSD51Zo2BjfPKxjLMzVAoFOo6TLzvugK3qNmRxsT5Kt0Rwl2UVW+pwz5J4Lh8MS9BlOSi81RlyfD0nKdDdZb6O5A4wosDDqsx/7PIx9v+Pw9cGRWufLXswqDXvV11OMbQvA4PmxuaXcAlrHJ0ssxiv8cY/k/8SkwpzV6dgHVfuqWPdVLhk0o1Yxis9BDG/YdQAE6csj3hnXfmfM52eE8lVZet7AJCSM/AwuP036CuU5HpwTYpX7lJzxGWQpLKRY6DI7NmcmuxsY7w+gbrfCsVYxhpA8iso8VLNz1PQ+Jy2HS547KNF1z3/DHt4ht797Is4xbwOk22W/LIqCAUBr+NEYiFbJhhM=



# Slack Notifications:
#       Based on: https://docs.travis-ci.com/user/notifications/#configuring-slack-notifications

  # slack:
  #   rooms:
  #     - <account>:<token>#development
  #     - <account>:<token>#general

  # notifications:
  #   slack: '<account>:<token>#development'

  # Utilizo
  # travis encrypt via-glaciar:20mXVmmmmmmmmmmmmGqfnYF0  --add notifications.slack.rooms

# https://docs.travis-ci.com/user/customizing-the-build/
# Travis build lifecycle, including three optional deployment steps

  # OPTIONAL Install apt addons
  # OPTIONAL Install cache components
  # before_install
  # install
  # before_script
  # script
  # OPTIONAL before_cache (for cleaning up cache)
  # after_success or after_failure
  # OPTIONAL before_deploy
  # OPTIONAL deploy
  # OPTIONAL after_deploy
  # after_script


# About Chrome Setup
#  https://gist.github.com/AhsanAyaz/820d40da5d1aa45c138f9e55d5193d34
#  You can avoid all the setup by using Travis' Chrome addon and their provided xvfb-run wrapper.
    #  addons:
    #   chrome: stable

    #  script:
    #   - npm run lint
    #   - npm run test:headless
    #   - npm run build
    #   - xvfb-run npm run e2e


# Para Firebase Hosting
#   https://medium.com/@jamzi/continuous-everything-with-angular-travis-ci-firebase-and-greenkeeper-6656543bd826

    # before_script:
    #    - npm install -g firebase-tools
    #    - npm install -g @angular/cli

    # script:
    #    - ng build --prod --aot

    # after_success:
    #    - firebase deploy --token $FIREBASE_TOKEN


# Secure Environment Variables With Travis CI
#   https://brettdewoody.com/secure-environment-variables-with-travis/
# gem install travis
# travis encrypt DB_URL=super_secret
# travis encrypt DB_URL=super_secret --add env

