language: node_js
node_js: 9.0.0
dist: trusty
sudo: required
branches:
  only:
    - master
    - develop

cache:
  directories: SimpleApp/node_modules

before_install:
  cd SimpleApp

before_script:
  - npm install -g @angular/cli

script:
  - ng build --aot

deploy:
  - provider: heroku
    api_key:
      secure: $HEROKU_KEY_USER_PABLOIN
    app:
      master: cicd-simple-app
      develop: cicd-simple-app-dev
    on:
      repo: Pabloin/CI-CD-app-Angular-Travis-Heroku

notifications:
  slack:
    rooms:
      secure: nnNZ17pRb6CEAg370T8IwxwqnAU/lSX07jhLdj2mF1SqoFLDep76g/yneGA4wHQmI8Z64+r+jr5QqO630ewq3UVquTd9XdHbYv/y2CXSKnqOPVcYTll15z1oV2xiH2phsxK767AoxpMKgBjaGUVJ+p5bmSgPchCJM8ONMKF/w35QYfnM/dH+VEfIaPplgZ0i578t8AGlkOi5tEABlrOLKGtX/nfP5LDpMqqAOO5hncUuWl/zmgO7crBeWdDDONvDFAzsCUL7Udo3KSXzJARmUFpt8mZ0tuKMsuenhMu2FoYS8gwqB2hCidTbAUNv6nkgYNAjWTc6U2u9CPurYn6am5FfGZbhA0325l7gEeq39+Ffgx1N48UUbzNSF+qjHZhTaJcJFGUOMRMTiAlGxIPUWP0xYhUU+FLs/MSSjLa0zacWX+V49pb6QZ07qRG7W8SokcxLpVVEOW8RDhTAzkgdvcUml5irNOSaD118usc9K/jUOF+5zaxA9kBbLgwyXFFQwt/XJZM4ewjRx0ArFMaBNy1KtPHf/VKFYT0LcXxa1+518ccw+wS9ss4dZXFagQOHdj/qf/6iVHh6hO2u4DDXTnNUrknNlQWkjdlJ3YetULXFLNuDhL4MvyPc+jnYw+dxWDNRL22Z5bf+yD2zFvwsf3Qr4LYBu0r/w/wM4hAuJNE=



# Slack Notifications:
#       Based on: https://docs.travis-ci.com/user/notifications/#configuring-slack-notifications

  # slack:
  #   rooms:
  #     - <account>:<token>#development
  #     - <account>:<token>#general

  # notifications:
  #   slack: '<account>:<token>#development'

  # Utilizo
  # travis encrypt via-glaciar:20mXVmmmmmmmmmmmmGqfnYF0  --add notifications.slack.rooms

# https://docs.travis-ci.com/user/customizing-the-build/
# Travis build lifecycle, including three optional deployment steps

  # OPTIONAL Install apt addons
  # OPTIONAL Install cache components
  # before_install
  # install
  # before_script
  # script
  # OPTIONAL before_cache (for cleaning up cache)
  # after_success or after_failure
  # OPTIONAL before_deploy
  # OPTIONAL deploy
  # OPTIONAL after_deploy
  # after_script


# About Chrome Setup
#  https://gist.github.com/AhsanAyaz/820d40da5d1aa45c138f9e55d5193d34
#  You can avoid all the setup by using Travis' Chrome addon and their provided xvfb-run wrapper.
    #  addons:
    #   chrome: stable

    #  script:
    #   - npm run lint
    #   - npm run test:headless
    #   - npm run build
    #   - xvfb-run npm run e2e


# Para Firebase Hosting
#   https://medium.com/@jamzi/continuous-everything-with-angular-travis-ci-firebase-and-greenkeeper-6656543bd826

    # before_script:
    #    - npm install -g firebase-tools
    #    - npm install -g @angular/cli

    # script:
    #    - ng build --prod --aot

    # after_success:
    #    - firebase deploy --token $FIREBASE_TOKEN


# Secure Environment Variables With Travis CI
#   https://brettdewoody.com/secure-environment-variables-with-travis/
# gem install travis
# travis encrypt DB_URL=super_secret
# travis encrypt DB_URL=super_secret --add env